Mark move_pages04 as known issue
openSUSE/kernel-qe pull request #9
Opened 2024-10-23 13:15 UTC by Avinesh

move_pages04 is expected to fail on kernels <6.12 due to wrong errno being returned.

https://lore.kernel.org/ltp/20241008135934.2491333-2-david@redhat.com/

2024-10-23 13:44 UTC, mdoucha requested changes

2024-10-23 20:15 UTC, Avinesh commented on ltp_known_issues.yaml
> +      message: expected to fail for kernels <6.12 [https://lore.kernel.org/ltp/20241008135934.2491333-2-david@redhat.com/]
Thanks for the suggestion. Please review updated version.

2024-10-24 07:49 UTC, pevik commented on ltp_known_issues.yaml
> +      message: expected to fail for kernels <6.12 [https://lore.kernel.org/ltp/20241008135934.2491333-2-david@redhat.com/]
LGTM. nit: why square brackets for URL?

2024-10-24 07:49 UTC, pevik approved these changes

2024-10-24 07:57 UTC, mdoucha approved these changes
LGTM

2024-10-24 13:12 UTC, merged